### ISSUE TITLE
Add information about vue3-sdk to the Readme of vue-sdk

### ISSUE THREAD

**Issue by wendelb** [bloomreach/spa-sdk#18]
Hi,

I was pointed to the `vue-sdk` npm package and tried to use it. Sadly it does not work with my vue3 application. And then I was a bit disappointed to find out, that there seems to be no version of the sdk that is compatible with vue 3. The readme even states as much:

> We are looking into updating to Vue 3 when possible which [does support multi-root templates](https://v3.vuejs.org/guide/migration/fragments.html#_2-x-syntax) without extra magic.

Some days later, I found the `vue3-sdk`. But it is missing in all documentation pages. Can you please add a reference to it in the `vue-sdk` Readme as well as in the developer documentation (e.g. https://documentation.bloomreach.com/content/docs/bloomreach-spa-sdk and https://xmdocumentation.bloomreach.com/library/concepts/spa-integration/sdks.html)

**Comment by beetlerom** [comment]
@wendelb We have recently launched the vue3 SDK and are gathering feedback from our customers & partners. For this reason, the vue3 SDK is only mentioned in the documentation in the README on Github and not yet in the public docs. We do plan to add that soon. Thank you for the feedback!

**Comment by joerideg** [comment]
@wendelb I will pass on the message to the documentation team as well as put a reference in the vue 2 sdk readme
