### ISSUE TITLE
Axios update

### ISSUE THREAD

**Issue by ennair** [bloomreach/spa-sdk#21]
I see that the sdk is still using axios 0.26.1, which is quite old. Is it possible to update this to the newest version of axios (version 1.4.0)? 

SDK package.json: https://github.com/bloomreach/spa-sdk/blob/spa-sdk-22.0.0/examples/next/package.json
Axios releases: https://github.com/axios/axios/releases

**Comment by beetlerom** [comment]
Hi @ennair. Thanks for the feedback, we plan to improve the example apps. in the future and we can update to a newer version then. 

Just to be clear, that is just the example app., the SDK does not use axios or any particular version of it. 

You may use any version of axios in your project, just pass along an object with the [required type](https://bloomreach.github.io/spa-sdk/modules/index._internal_.html#HttpClientConfig) to the httpConfig property in the [initialize function](https://bloomreach.github.io/spa-sdk/modules/index._internal_.html#HttpClientConfig).

**Comment by joerideg** [comment]
Hi @ennair ,
Yes you just need any http client that matches with https://bloomreach.github.io/spa-sdk/modules/index.Internals.html#HttpClient 

It seems the latest Axios still supports that partial type. https://axios-http.com/docs/req_config
