### ISSUE TITLE
Is this repository open for contribution?

### ISSUE THREAD

**Issue by cosieLq** [bloomreach/spa-sdk#23]
I'm wondering if this repo is open for contribution/pull requests.
There are several PRs, but they're rather old.

If the answer is yes, what are the constraints?

**Comment by beetlerom** [comment]
@cosieLq The repository is definitely open to contributions and very much appreciated!
This repository is a mirror of a private GitLab repository hosted within Bloomreach so we will not be able to merge your changes directly in GitHub, but they will be accepted and be part of the package :)
Very soon we will move the repository to GitHub and make it the main repository.
