### ISSUE TITLE
Example Next 13/14

### ISSUE THREAD

**Issue by Andrekra** [bloomreach/spa-sdk#27]
Hi, can you provide an example how to use the SDK with Next 13/14 with specifically the [App router](https://nextjs.org/docs/app/building-your-application/routing) and fetch (to benefit of[ request memoization](https://nextjs.org/docs/app/building-your-application/caching#request-memoization)). It's API is quite different compared to the Pages Router (for example no getServersideProps, a new generateMetada method that relies on using fetch for caching). For now they live side by side, but at some point they will be removed.

**Comment by ValeriaPtah** [comment]
Hi! We don't have an official support and an example app for Next 13/14 yet, but it makes sense to upgrade the SDK to support these newer versions. We put a project on our roadmap to do just that. I'll keep this question updated for when we have specifics to add.

**Comment by MrSharpp** [comment]
I want it too
