### ISSUE TITLE
Upgrade path improvements

### ISSUE THREAD

**Issue by beetlerom** [bloomreach/spa-sdk#3]

**Comment by beetlerom** [comment]
@DavidSint What version are you using?

**Comment by Sohitri216** [comment]
Hi @beetlerom I have tried upgrading the bloomreach sdk version to 17.1.0. 
npm audit report shows a critical vulnerability related to @xmldom/xmldom 

```
@xmldom/xmldom  <0.7.7
Severity: critical
xmldom allows multiple root nodes in a DOM - https://github.com/advisories/GHSA-crh6-fp67-6883
```

Can you please suggest a fix for this? Thanks.

**Comment by beetlerom** [comment]
@Sohitri216 Yes a new vulnerability was discovered right after our previous patch, we will be releasing 17.1.1 soon to address that as well as others.

**Comment by DavidSint** [comment]
@beetlerom we're using v15, but as it relates to this issue, I was just saying that having an upgrade guide for versions that break changes is a general best-practice, I'd have thought. This is regardless of the versions that are being upgraded.

**Comment by DavidSint** [comment]
Here is an example from Next.js: https://nextjs.org/docs/upgrading

**Comment by hachok** [comment]
Sounds good to me! We can create an upgrading guide. @beetlerom, should we discuss it in the next chapter meeting?

**Comment by beetlerom** [comment]
@DavidSint @hachok 💯 Very much in line here, we need such a guide.

@DavidSint I was just curious what version you are using to get an idea of how far back we want the migration guide to go. v15 was on my mind, but not sure about v14 yet. Thanks!
