### ISSUE TITLE
xmldom allows multiple root nodes in a DOM

### ISSUE THREAD

**Issue by beetlerom** [bloomreach/spa-sdk#4]
See [dependabot alert](https://github.com/bloomreach/spa-sdk/security/dependabot/127) for details.

**Comment by hachok** [comment]
It should be fixed in [17.1.1](https://github.com/bloomreach/spa-sdk/releases/tag/spa-sdk-17.1.1)

**Comment by beetlerom** [comment]
@Sohitri216 This should address your security concern.
